Fix the nested test structure
```
io.kotest.core.spec.InvalidDslException: Cannot add a root test after the spec has been instantiated: test CRUD with Statements
```

`SimpleExamplesTests` adapted to extend `FunSpec` using Copilot.

Copilot could identify the cause but could not add the `FunSpecContainerScope` receiver to `crudTests` to resolve this issue in this simpler way, it inlines the function instead.