Add `readOnlyTransactionIsolationLevel` in `DatabaseClientConfig` and update `exposedReadOnlyTransaction` to use this value, which defaults to `Connection.TRANSACTION_READ_UNCOMMITTED`
This is updated because the follow exception occurs in https://github.com/huanshankeji/FrameworkBenchmarks/commit/382af3f4ac3586813449c51e3b38fce74964193c:

```
org.postgresql.util.PSQLException: Transaction isolation level 0 not supported.
```