Fix compilation errors such as ".../TransactionTests.kt:30:93 Unresolved reference 'withTransactionEither'." when running Gradle `test` by moving code to the `integrated` package
This is primarily caused by 2 `Transactions.kt` files in the same package in different modules. Also, `TransactionOrRollbackEitherTests.withTransactionOrRollback`'s type is slightly wrong.

Tried analyzing with Copilot first, but it didn't locate the cause.

Fix some KDoc link warnings for `Either.Left` and `Either.Right` BTW.